server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    mongodb:
        uri: mongodb://localhost:27017/auth_db

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG