server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://campus-auth-service.onrender.com
          predicates:
            - Path=/api/auth/**

        - id: student-service
          uri: https://campus-student-siva.onrender.com
          predicates:
            - Path=/api/students/**
          filters:
            - AuthenticationFilter

        - id: event-service
          uri: https://campus-event-siva.onrender.com
          predicates:
            - Path=/api/events/**
          filters:
            - AuthenticationFilter

        - id: faculty-service
          uri: https://campus-faculty-siva.onrender.com
          predicates:
            - Path=/api/faculty/**
          filters:
            - AuthenticationFilter

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970